import type { SupportedLanguageCode } from "@/lib/language/language-preferences";
import type { DiagnosisOption, DiagnosisQuestionDefinition } from "./diagnosis-models";
import { EMPLOYMENT_DIAGNOSIS_ENGINE_VERSION_3D } from "./diagnosis-version";

function option(code: string, en: string, fr: string, extra: Partial<DiagnosisOption> = {}): DiagnosisOption {
  return {
    code,
    label: { en, fr },
    ...extra
  };
}

const unknown = option("UNKNOWN", "I don't know yet", "Je ne sais pas encore", { answerState: "UNKNOWN", iconKey: "help" });
const declined = option("USER_DECLINED", "Prefer not to say", "Je préfère ne pas répondre", { answerState: "USER_DECLINED", iconKey: "lock" });
const notApplicable = option("NOT_APPLICABLE", "Not applicable", "Non applicable", { answerState: "NOT_APPLICABLE", iconKey: "minus" });

function q(definition: Omit<DiagnosisQuestionDefinition, "version" | "maximumDisplayLength"> & { maximumDisplayLength?: number }): DiagnosisQuestionDefinition {
  return {
    ...definition,
    maximumDisplayLength: definition.maximumDisplayLength ?? 160,
    version: EMPLOYMENT_DIAGNOSIS_ENGINE_VERSION_3D
  };
}

export const employmentDiagnosisQuestionRegistry: DiagnosisQuestionDefinition[] = [
  q({
    questionId: "work_authorisation_clarification",
    category: "WORK_ELIGIBILITY_CLARIFICATION",
    purpose: "Clarify lawful work eligibility only when Professional Identity is missing or uncertain.",
    promptKey: "diagnosis.workAuthorisation.prompt",
    helpTextKey: "diagnosis.workAuthorisation.help",
    title: { en: "Work authorisation", fr: "Autorisation de travail" },
    prompt: { en: "Which option best describes your current right to work?", fr: "Quelle option décrit le mieux votre droit actuel de travailler ?" },
    helpText: { en: "PATHZY asks this only to avoid unsafe or unsuitable employment steps. Nationality alone is not used.", fr: "PATHZY le demande seulement pour éviter des démarches d'emploi inadaptées. La nationalité seule n'est pas utilisée." },
    whyAsked: { en: "Some pathways require confirmed work authorisation or documents.", fr: "Certains parcours nécessitent une autorisation de travail ou des documents confirmés." },
    answerType: "SINGLE_SELECT",
    options: [
      option("CONFIRMED", "I can work legally", "Je peux travailler légalement"),
      option("RESTRICTED", "I have conditions or limits", "J'ai des conditions ou limites"),
      option("PENDING", "I am waiting for confirmation", "J'attends une confirmation"),
      option("NO_CONFIRMED_AUTHORISATION", "I do not have confirmed authorisation", "Je n'ai pas d'autorisation confirmée"),
      unknown,
      declined
    ],
    requiredness: "CONDITIONAL",
    sensitivity: "HIGH",
    eligibilityRules: [{ ruleId: "ask_when_work_authorisation_unknown", reason: "Professional Identity does not contain a reliable work authorisation status." }],
    skipRules: [{ ruleId: "skip_when_work_authorisation_confirmed", reason: "Confirmed identity facts are not asked again." }],
    branchRules: [{ ruleId: "legal_dependency_before_pathway", reason: "Work eligibility uncertainty affects safe pathway advice." }],
    affectedIntelligenceDimensions: ["WORK_ELIGIBILITY_READINESS"],
    affectedBarriers: ["LEGAL_OR_DOCUMENTATION_UNCERTAINTY"],
    affectedPathways: ["DIRECT_EMPLOYMENT", "PUBLIC_EMPLOYMENT_PROGRAMME", "SUPPORTED_EMPLOYMENT"],
    countryContextDependencies: ["work_authorisation_context"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 10
  }),
  q({
    questionId: "qualification_recognition_status",
    category: "COUNTRY_CONTEXT_CLARIFICATION",
    purpose: "Clarify recognition status where a foreign or regulated qualification may affect a pathway.",
    promptKey: "diagnosis.qualificationRecognition.prompt",
    helpTextKey: "diagnosis.qualificationRecognition.help",
    title: { en: "Qualification recognition", fr: "Reconnaissance du diplôme" },
    prompt: { en: "Has your qualification been recognised for the country where you want to work?", fr: "Votre diplôme a-t-il été reconnu dans le pays où vous voulez travailler ?" },
    helpText: { en: "This does not decide your eligibility. It tells PATHZY whether recognition evidence may be needed.", fr: "Cela ne décide pas de votre admissibilité. Cela indique à PATHZY si une preuve de reconnaissance peut être nécessaire." },
    whyAsked: { en: "Foreign or regulated qualifications can need extra evidence before applications.", fr: "Les diplômes étrangers ou réglementés peuvent nécessiter des preuves supplémentaires avant de postuler." },
    answerType: "SINGLE_SELECT",
    options: [option("RECOGNISED", "Yes, recognised", "Oui, reconnu"), option("IN_PROGRESS", "In progress", "En cours"), option("NOT_RECOGNISED", "Not recognised yet", "Pas encore reconnu"), unknown, notApplicable],
    requiredness: "CONDITIONAL",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "ask_foreign_or_regulated_qualification", reason: "Country context says qualification recognition may affect confidence." }],
    skipRules: [{ ruleId: "skip_when_no_qualification_dependency", reason: "No recognition dependency has been detected." }],
    branchRules: [{ ruleId: "recognition_dependency", reason: "Recognition uncertainty affects professional and bridging pathways." }],
    affectedIntelligenceDimensions: ["QUALIFICATION_READINESS", "EVIDENCE_READINESS"],
    affectedBarriers: ["QUALIFICATION_RECOGNITION_UNCERTAINTY"],
    affectedPathways: ["QUALIFICATION_RECOGNITION", "BRIDGING_EDUCATION", "PROFESSIONAL_EMPLOYMENT"],
    countryContextDependencies: ["qualification_framework"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 20
  }),
  q({
    questionId: "security_registration_evidence",
    category: "DOCUMENTATION",
    purpose: "Clarify registration evidence only for security-related goals or experience.",
    promptKey: "diagnosis.securityRegistration.prompt",
    helpTextKey: "diagnosis.securityRegistration.help",
    title: { en: "Security registration", fr: "Enregistrement sécurité" },
    prompt: { en: "Do you have current evidence of your security registration or licence?", fr: "Avez-vous une preuve actuelle de votre enregistrement ou licence de sécurité ?" },
    helpText: { en: "PATHZY will not make a legal decision. It can remind you when evidence may be needed.", fr: "PATHZY ne prendra pas de décision juridique. Il peut rappeler quand une preuve peut être nécessaire." },
    whyAsked: { en: "Some security roles need proof before applications are useful.", fr: "Certains postes de sécurité nécessitent une preuve avant que les candidatures soient utiles." },
    answerType: "DOCUMENT_AVAILABLE",
    options: [option("AVAILABLE", "Yes, I have it", "Oui, je l'ai"), option("EXPIRED_OR_OLD", "I have an old or expired document", "J'ai un document ancien ou expiré"), option("NOT_AVAILABLE", "Not yet", "Pas encore"), unknown, notApplicable],
    requiredness: "CONDITIONAL",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "ask_security_goal_or_experience", reason: "Security goal, experience, or licence dependency detected." }],
    skipRules: [{ ruleId: "skip_non_security", reason: "Not relevant to the current pathway." }],
    branchRules: [{ ruleId: "evidence_before_application", reason: "Missing registration evidence changes document preparation." }],
    affectedIntelligenceDimensions: ["DOCUMENT_READINESS", "WORK_ELIGIBILITY_READINESS"],
    affectedBarriers: ["LICENCE_OR_REGISTRATION_EVIDENCE_MISSING"],
    affectedPathways: ["LICENCE_OR_CERTIFICATE", "SKILLED_EMPLOYMENT"],
    countryContextDependencies: ["job_level_context.security"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 25
  }),
  q({
    questionId: "immediate_income_need",
    category: "IMMEDIATE_INCOME_NEED",
    purpose: "Understand urgency so PATHZY can prioritise practical next steps without judging the user.",
    promptKey: "diagnosis.incomeNeed.prompt",
    helpTextKey: "diagnosis.incomeNeed.help",
    title: { en: "Income urgency", fr: "Urgence de revenu" },
    prompt: { en: "How urgent is it for you to earn income?", fr: "À quel point est-il urgent pour vous de gagner un revenu ?" },
    helpText: { en: "This changes priority and support. It does not reduce your potential.", fr: "Cela change les priorités et le soutien. Cela ne réduit pas votre potentiel." },
    whyAsked: { en: "Urgency affects whether PATHZY suggests fast income routes before longer-term steps.", fr: "L'urgence influence si PATHZY propose des routes de revenu rapides avant les étapes à long terme." },
    answerType: "SINGLE_SELECT",
    options: [option("URGENT", "I need income urgently", "J'ai besoin d'un revenu rapidement"), option("SOON", "Within the next few months", "Dans les prochains mois"), option("FLEXIBLE", "I can plan longer term", "Je peux planifier à plus long terme"), unknown, declined],
    requiredness: "REQUIRED",
    sensitivity: "HIGH",
    eligibilityRules: [{ ruleId: "always_high_value", reason: "Income urgency affects support intensity." }],
    skipRules: [],
    branchRules: [{ ruleId: "urgent_income_shortens_path", reason: "Urgent income moves practical access and immediate pathways earlier." }],
    affectedIntelligenceDimensions: ["PRACTICAL_ACCESS_READINESS", "CONFIDENCE_AND_SUPPORT_READINESS"],
    affectedBarriers: ["PRACTICAL_ACCESS_CONSTRAINT"],
    affectedPathways: ["TEMPORARY_WORK", "PART_TIME_WORK", "INFORMAL_OR_COMMUNITY_WORK", "PUBLIC_EMPLOYMENT_PROGRAMME"],
    countryContextDependencies: ["practical_access_context"],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 30
  }),
  q({
    questionId: "job_search_activity_recent",
    category: "JOB_SEARCH_ACTIVITY",
    purpose: "Understand current job-search activity without requiring long explanations.",
    promptKey: "diagnosis.jobSearch.prompt",
    helpTextKey: "diagnosis.jobSearch.help",
    title: { en: "Recent job search", fr: "Recherche récente" },
    prompt: { en: "In the last month, what best describes your job search?", fr: "Au cours du dernier mois, qu'est-ce qui décrit le mieux votre recherche ?" },
    helpText: { en: "This helps PATHZY separate preparation needs from opportunity-search needs.", fr: "Cela aide PATHZY à distinguer la préparation de la recherche d'opportunités." },
    whyAsked: { en: "Application activity affects opportunity and application readiness.", fr: "L'activité de candidature influence la préparation aux opportunités et aux candidatures." },
    answerType: "SINGLE_SELECT",
    options: [option("NOT_STARTED", "I have not started applying", "Je n'ai pas encore commencé"), option("SEARCHING_NOT_APPLYING", "I am searching but not applying yet", "Je cherche mais je ne postule pas encore"), option("FEW_APPLICATIONS", "I sent a few applications", "J'ai envoyé quelques candidatures"), option("MANY_APPLICATIONS", "I am applying often", "Je postule souvent"), unknown],
    requiredness: "REQUIRED",
    sensitivity: "LOW",
    eligibilityRules: [{ ruleId: "always_high_value", reason: "Current activity is needed for meaningful diagnosis." }],
    skipRules: [],
    branchRules: [{ ruleId: "activity_drives_application_quality", reason: "Active applicants may need application quality and follow-up questions." }],
    affectedIntelligenceDimensions: ["OPPORTUNITY_READINESS", "APPLICATION_READINESS"],
    affectedBarriers: ["JOB_SEARCH_ACTIVITY_GAP"],
    affectedPathways: ["DIRECT_EMPLOYMENT", "ENTRY_LEVEL_EMPLOYMENT"],
    countryContextDependencies: [],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 40
  }),
  q({
    questionId: "application_quality_feedback",
    category: "APPLICATION_QUALITY",
    purpose: "Check whether applications are getting responses without blaming the user.",
    promptKey: "diagnosis.applicationQuality.prompt",
    helpTextKey: "diagnosis.applicationQuality.help",
    title: { en: "Application results", fr: "Résultats des candidatures" },
    prompt: { en: "When you apply, what usually happens?", fr: "Quand vous postulez, que se passe-t-il le plus souvent ?" },
    helpText: { en: "This guides whether PATHZY should focus on documents, job fit, or follow-up.", fr: "Cela guide PATHZY vers les documents, l'adéquation des postes ou le suivi." },
    whyAsked: { en: "Repeated silence can mean document, targeting, or market issues.", fr: "Des silences répétés peuvent indiquer un problème de document, de ciblage ou de marché." },
    answerType: "SINGLE_SELECT",
    options: [option("NO_RESPONSES", "I rarely get responses", "Je reçois rarement des réponses"), option("SOME_RESPONSES", "I sometimes get responses", "Je reçois parfois des réponses"), option("INTERVIEWS", "I get interviews", "J'obtiens des entretiens"), option("NOT_APPLIED", "I have not applied yet", "Je n'ai pas encore postulé"), unknown],
    requiredness: "CONDITIONAL",
    sensitivity: "LOW",
    eligibilityRules: [{ ruleId: "ask_when_job_search_active", reason: "Application quality matters when the user has applied or is ready to apply." }],
    skipRules: [{ ruleId: "skip_when_not_searching", reason: "Not useful before the user starts applying." }],
    branchRules: [{ ruleId: "responses_drive_document_or_interview_focus", reason: "Responses indicate whether to focus on documents or interviews." }],
    affectedIntelligenceDimensions: ["APPLICATION_READINESS", "DOCUMENT_READINESS", "INTERVIEW_READINESS"],
    affectedBarriers: ["APPLICATION_QUALITY_UNCLEAR"],
    affectedPathways: ["DIRECT_EMPLOYMENT", "ENTRY_LEVEL_EMPLOYMENT"],
    countryContextDependencies: [],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 50
  }),
  q({
    questionId: "interview_history_recent",
    category: "INTERVIEW_HISTORY",
    purpose: "Know whether interview preparation is a current blocker.",
    promptKey: "diagnosis.interviewHistory.prompt",
    helpTextKey: "diagnosis.interviewHistory.help",
    title: { en: "Interview experience", fr: "Entretiens" },
    prompt: { en: "Have you had interviews recently?", fr: "Avez-vous eu des entretiens récemment ?" },
    helpText: { en: "PATHZY uses this to decide whether interview support should come sooner.", fr: "PATHZY l'utilise pour savoir si la préparation aux entretiens doit venir plus tôt." },
    whyAsked: { en: "Interview history affects interview readiness and support timing.", fr: "L'historique des entretiens influence la préparation et le moment du soutien." },
    answerType: "SINGLE_SELECT",
    options: [option("NONE", "No recent interviews", "Aucun entretien récent"), option("INVITED_NOT_CONFIDENT", "Yes, but I need confidence", "Oui, mais j'ai besoin de confiance"), option("COMPLETED_WAITING", "Yes, and I am waiting for feedback", "Oui, et j'attends un retour"), option("COMFORTABLE", "Yes, I feel prepared", "Oui, je me sens préparé"), unknown],
    requiredness: "CONDITIONAL",
    sensitivity: "LOW",
    eligibilityRules: [{ ruleId: "ask_when_applying_or_getting_responses", reason: "Interview preparation matters once applications are active." }],
    skipRules: [{ ruleId: "skip_before_applications", reason: "Not a priority before applications begin." }],
    branchRules: [],
    affectedIntelligenceDimensions: ["INTERVIEW_READINESS", "CONFIDENCE_AND_SUPPORT_READINESS"],
    affectedBarriers: ["INTERVIEW_PREPARATION_GAP"],
    affectedPathways: ["DIRECT_EMPLOYMENT", "PROFESSIONAL_EMPLOYMENT"],
    countryContextDependencies: [],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 60
  }),
  q({
    questionId: "transport_shift_access",
    category: "PRACTICAL_ACCESS",
    purpose: "Identify real-world transport or shift constraints separately from capability.",
    promptKey: "diagnosis.transport.prompt",
    helpTextKey: "diagnosis.transport.help",
    title: { en: "Transport and shifts", fr: "Transport et horaires" },
    prompt: { en: "What transport or shift limits should PATHZY consider?", fr: "Quelles limites de transport ou d'horaires PATHZY doit-il prendre en compte ?" },
    helpText: { en: "Practical access changes which steps are realistic. It is not a judgement of ability.", fr: "L'accès pratique change les étapes réalistes. Ce n'est pas un jugement de capacité." },
    whyAsked: { en: "Transport and shifts can affect job fit, application timing, and support.", fr: "Transport et horaires peuvent influencer l'adéquation, le timing et le soutien." },
    answerType: "MULTI_SELECT",
    options: [option("NO_MAJOR_LIMIT", "No major limit", "Pas de limite majeure"), option("TRANSPORT_LIMIT", "Transport is difficult or expensive", "Le transport est difficile ou coûteux"), option("SHIFT_LIMIT", "Some shifts are difficult", "Certains horaires sont difficiles"), option("LOCAL_ONLY", "I need local options", "J'ai besoin d'options locales"), unknown, declined],
    requiredness: "REQUIRED",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "always_high_value", reason: "Practical access affects realistic employment action." }],
    skipRules: [],
    branchRules: [{ ruleId: "access_constraints_adjust_path", reason: "Access constraints prioritize practical options." }],
    affectedIntelligenceDimensions: ["PRACTICAL_ACCESS_READINESS"],
    affectedBarriers: ["PRACTICAL_ACCESS_CONSTRAINT"],
    affectedPathways: ["PART_TIME_WORK", "TEMPORARY_WORK", "SUPPORTED_EMPLOYMENT"],
    countryContextDependencies: ["region_context", "practical_access_context"],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 70
  }),
  q({
    questionId: "device_internet_access",
    category: "DIGITAL_ACCESS",
    purpose: "Adapt support for users with limited device or internet access.",
    promptKey: "diagnosis.digitalAccess.prompt",
    helpTextKey: "diagnosis.digitalAccess.help",
    title: { en: "Phone and internet", fr: "Téléphone et internet" },
    prompt: { en: "What digital access do you usually have?", fr: "Quel accès numérique avez-vous généralement ?" },
    helpText: { en: "Limited access changes support steps only. It does not reduce your capability.", fr: "Un accès limité change seulement les étapes de soutien. Cela ne réduit pas vos capacités." },
    whyAsked: { en: "PATHZY can keep steps shorter and practical when data or devices are limited.", fr: "PATHZY peut garder les étapes courtes et pratiques si les données ou appareils sont limités." },
    answerType: "SINGLE_SELECT",
    options: [option("RELIABLE", "Reliable phone/computer and internet", "Téléphone/ordinateur et internet fiables"), option("SMARTPHONE_ONLY", "Mostly a smartphone", "Surtout un smartphone"), option("LIMITED_DATA", "Limited data or unreliable internet", "Données limitées ou internet instable"), option("SHARED_DEVICE", "Shared or borrowed device", "Appareil partagé ou emprunté"), unknown],
    requiredness: "REQUIRED",
    sensitivity: "LOW",
    eligibilityRules: [{ ruleId: "always_high_value", reason: "Digital access affects how PATHZY presents actions." }],
    skipRules: [],
    branchRules: [{ ruleId: "limited_access_plain_language", reason: "Limited access can trigger assisted or high-guidance presentation." }],
    affectedIntelligenceDimensions: ["DIGITAL_ACCESS_READINESS", "PRACTICAL_ACCESS_READINESS"],
    affectedBarriers: ["PRACTICAL_ACCESS_CONSTRAINT"],
    affectedPathways: ["SUPPORTED_EMPLOYMENT", "PUBLIC_EMPLOYMENT_PROGRAMME"],
    countryContextDependencies: ["practical_access_context.digital"],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 80
  }),
  q({
    questionId: "reading_writing_comfort",
    category: "COMMUNICATION_AND_LITERACY",
    purpose: "Choose support style without treating literacy as capability.",
    promptKey: "diagnosis.literacy.prompt",
    helpTextKey: "diagnosis.literacy.help",
    title: { en: "Reading and writing comfort", fr: "Aisance en lecture et écriture" },
    prompt: { en: "How much help would you like with reading or writing job steps?", fr: "Quel niveau d'aide souhaitez-vous pour lire ou écrire les étapes d'emploi ?" },
    helpText: { en: "This only changes how PATHZY supports you.", fr: "Cela change seulement la manière dont PATHZY vous accompagne." },
    whyAsked: { en: "Plain-language mode and examples can make the process easier.", fr: "Le mode simple et les exemples peuvent rendre le processus plus facile." },
    answerType: "SINGLE_SELECT",
    options: [option("COMFORTABLE", "I am comfortable", "Je suis à l'aise"), option("SOME_HELP", "Some help would be useful", "Un peu d'aide serait utile"), option("HIGH_GUIDANCE", "I want simple steps and examples", "Je veux des étapes simples et des exemples"), declined],
    requiredness: "OPTIONAL",
    sensitivity: "HIGH",
    eligibilityRules: [{ ruleId: "ask_when_support_needed_or_low_digital_confidence", reason: "Support mode helps PATHZY reduce overload." }],
    skipRules: [{ ruleId: "defer_optional_after_critical", reason: "Ask after critical blockers unless support intensity is high." }],
    branchRules: [{ ruleId: "set_presentation_mode", reason: "Answer can switch diagnosis presentation to plain language or high guidance." }],
    affectedIntelligenceDimensions: ["CONFIDENCE_AND_SUPPORT_READINESS"],
    affectedBarriers: ["COMMUNICATION_SUPPORT_NEEDED"],
    affectedPathways: ["SUPPORTED_EMPLOYMENT"],
    countryContextDependencies: ["language_context"],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 90
  }),
  q({
    questionId: "documentation_availability",
    category: "DOCUMENTATION",
    purpose: "Know whether key documents are ready without requesting document contents.",
    promptKey: "diagnosis.documentation.prompt",
    helpTextKey: "diagnosis.documentation.help",
    title: { en: "Documents", fr: "Documents" },
    prompt: { en: "Which documents can you access when applying?", fr: "Quels documents pouvez-vous utiliser pour postuler ?" },
    helpText: { en: "PATHZY only needs availability here, not private document contents.", fr: "PATHZY a seulement besoin de savoir ce qui est disponible ici, pas du contenu privé." },
    whyAsked: { en: "Document gaps can block otherwise suitable applications.", fr: "Les documents manquants peuvent bloquer des candidatures autrement adaptées." },
    answerType: "MULTI_SELECT",
    options: [option("ID_OR_WORK_DOCS", "Identity or work documents", "Documents d'identité ou de travail"), option("CERTIFICATES", "Certificates or qualifications", "Certificats ou diplômes"), option("REFERENCES", "References", "Références"), option("CV_READY", "A CV", "Un CV"), option("NONE_READY", "None ready yet", "Aucun prêt pour le moment"), unknown, declined],
    requiredness: "REQUIRED",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "always_high_value", reason: "Documents affect evidence and application readiness." }],
    skipRules: [],
    branchRules: [{ ruleId: "document_gaps_to_actions", reason: "Document availability shapes next evidence actions." }],
    affectedIntelligenceDimensions: ["DOCUMENT_READINESS", "EVIDENCE_READINESS", "APPLICATION_READINESS"],
    affectedBarriers: ["DOCUMENTATION_GAP"],
    affectedPathways: ["DIRECT_EMPLOYMENT", "ENTRY_LEVEL_EMPLOYMENT", "LICENCE_OR_CERTIFICATE"],
    countryContextDependencies: ["evidence_requirements"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 100
  }),
  q({
    questionId: "informal_experience_evidence",
    category: "INFORMAL_EXPERIENCE",
    purpose: "Capture informal or community work evidence without forcing formal employment history.",
    promptKey: "diagnosis.informalExperience.prompt",
    helpTextKey: "diagnosis.informalExperience.help",
    title: { en: "Informal experience", fr: "Expérience informelle" },
    prompt: { en: "Do you have informal, family, community, freelance, or unpaid experience PATHZY should recognise?", fr: "Avez-vous une expérience informelle, familiale, communautaire, freelance ou bénévole que PATHZY doit reconnaître ?" },
    helpText: { en: "Informal experience can still show reliability, skills, and evidence.", fr: "L'expérience informelle peut montrer la fiabilité, les compétences et des preuves." },
    whyAsked: { en: "Some users have strong evidence outside formal job titles.", fr: "Certaines personnes ont de fortes preuves en dehors des postes formels." },
    answerType: "SINGLE_SELECT",
    options: [option("YES_WITH_REFERENCE", "Yes, and someone can confirm it", "Oui, et quelqu'un peut le confirmer"), option("YES_NO_REFERENCE", "Yes, but no reference yet", "Oui, mais pas encore de référence"), option("NO", "No", "Non"), unknown],
    requiredness: "CONDITIONAL",
    sensitivity: "LOW",
    eligibilityRules: [{ ruleId: "ask_when_no_formal_experience_or_service_goal", reason: "Informal experience can prevent under-assessment." }],
    skipRules: [{ ruleId: "skip_when_strong_formal_evidence", reason: "Strong formal evidence already exists." }],
    branchRules: [{ ruleId: "suggest_identity_experience", reason: "A yes answer can create a confirmation-required identity suggestion." }],
    affectedIntelligenceDimensions: ["EXPERIENCE_READINESS", "EVIDENCE_READINESS"],
    affectedBarriers: ["EVIDENCE_GAP"],
    affectedPathways: ["INFORMAL_OR_COMMUNITY_WORK", "ENTRY_LEVEL_EMPLOYMENT", "SELF_EMPLOYMENT"],
    countryContextDependencies: ["job_level_context.service_roles"],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 110
  }),
  q({
    questionId: "mobility_radius",
    category: "MOBILITY_AND_LOCATION",
    purpose: "Understand realistic location range when it has not been confirmed elsewhere.",
    promptKey: "diagnosis.mobility.prompt",
    helpTextKey: "diagnosis.mobility.help",
    title: { en: "Where you can work", fr: "Où vous pouvez travailler" },
    prompt: { en: "Which work locations are realistic for you right now?", fr: "Quels lieux de travail sont réalistes pour vous maintenant ?" },
    helpText: { en: "This helps avoid suggestions that are too far or impractical.", fr: "Cela évite des suggestions trop éloignées ou peu pratiques." },
    whyAsked: { en: "Mobility affects opportunity readiness and practical access.", fr: "La mobilité influence les opportunités et l'accès pratique." },
    answerType: "LOCATION_RADIUS",
    options: [option("LOCAL_ONLY", "Local area only", "Zone locale seulement"), option("NEARBY_AREAS", "Nearby areas", "Zones proches"), option("RELOCATE", "I can relocate", "Je peux déménager"), option("REMOTE_OR_HYBRID", "Remote or hybrid", "À distance ou hybride"), unknown],
    requiredness: "CONDITIONAL",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "ask_when_location_or_relocation_unclear", reason: "Location range is not confirmed." }],
    skipRules: [{ ruleId: "skip_when_location_preferences_known", reason: "Known canonical facts should not be asked again." }],
    branchRules: [],
    affectedIntelligenceDimensions: ["OPPORTUNITY_READINESS", "PRACTICAL_ACCESS_READINESS"],
    affectedBarriers: ["PRACTICAL_ACCESS_CONSTRAINT"],
    affectedPathways: ["DIRECT_EMPLOYMENT", "REMOTE_WORK", "TEMPORARY_WORK"].filter((code) => code !== "REMOTE_WORK") as DiagnosisQuestionDefinition["affectedPathways"],
    countryContextDependencies: ["region_context"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 120
  }),
  q({
    questionId: "care_responsibilities",
    category: "CARE_RESPONSIBILITIES",
    purpose: "Adapt timing and work-pattern suggestions where care responsibilities matter.",
    promptKey: "diagnosis.care.prompt",
    helpTextKey: "diagnosis.care.help",
    title: { en: "Care responsibilities", fr: "Responsabilités de soin" },
    prompt: { en: "Do care responsibilities affect the hours or location you can work?", fr: "Des responsabilités de soin influencent-elles vos horaires ou lieux de travail ?" },
    helpText: { en: "You can skip this. PATHZY asks only to make steps realistic.", fr: "Vous pouvez passer. PATHZY le demande seulement pour rendre les étapes réalistes." },
    whyAsked: { en: "Care responsibilities can affect suitable schedules and support needs.", fr: "Les responsabilités de soin peuvent influencer les horaires et le soutien." },
    answerType: "SINGLE_SELECT",
    options: [option("NO_LIMIT", "No major limit", "Pas de limite majeure"), option("SOME_LIMIT", "Some limits", "Quelques limites"), option("MAJOR_LIMIT", "Major limits", "Limites importantes"), declined, notApplicable],
    requiredness: "OPTIONAL",
    sensitivity: "HIGH",
    eligibilityRules: [{ ruleId: "ask_when_work_pattern_unclear", reason: "Work pattern may affect practical route planning." }],
    skipRules: [{ ruleId: "defer_sensitive_optional", reason: "Sensitive optional questions are not blockers." }],
    branchRules: [],
    affectedIntelligenceDimensions: ["PRACTICAL_ACCESS_READINESS", "CONFIDENCE_AND_SUPPORT_READINESS"],
    affectedBarriers: ["PRACTICAL_ACCESS_CONSTRAINT"],
    affectedPathways: ["PART_TIME_WORK", "SUPPORTED_EMPLOYMENT", "RETURN_TO_WORK"],
    countryContextDependencies: [],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 130
  }),
  q({
    questionId: "learning_development_willingness",
    category: "LEARNING_AND_DEVELOPMENT",
    purpose: "Understand whether learning pathways are practical now.",
    promptKey: "diagnosis.learning.prompt",
    helpTextKey: "diagnosis.learning.help",
    title: { en: "Learning options", fr: "Options d'apprentissage" },
    prompt: { en: "Are you open to short training, practice projects, or certificates if they help?", fr: "Êtes-vous ouvert à une courte formation, des projets pratiques ou des certificats si cela aide ?" },
    helpText: { en: "This helps PATHZY balance work-now and skill-building routes.", fr: "Cela aide PATHZY à équilibrer travail immédiat et développement de compétences." },
    whyAsked: { en: "Learning willingness affects skills-first and bridging pathways.", fr: "La volonté d'apprendre influence les parcours compétences et passerelles." },
    answerType: "SINGLE_SELECT",
    options: [option("YES_NOW", "Yes, now", "Oui, maintenant"), option("YES_IF_SHORT", "Yes, if it is short", "Oui, si c'est court"), option("NOT_NOW", "Not right now", "Pas maintenant"), unknown],
    requiredness: "OPTIONAL",
    sensitivity: "NONE",
    eligibilityRules: [{ ruleId: "ask_for_development_pathways", reason: "Learning routes may be useful." }],
    skipRules: [{ ruleId: "defer_optional", reason: "Optional refinement." }],
    branchRules: [],
    affectedIntelligenceDimensions: ["SKILLS_READINESS", "QUALIFICATION_READINESS"],
    affectedBarriers: ["SKILL_OR_QUALIFICATION_GAP"],
    affectedPathways: ["SKILLS_FIRST_TRANSITION", "BRIDGING_EDUCATION", "LEARNERSHIP"],
    countryContextDependencies: ["pathway_context"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 140
  }),
  q({
    questionId: "confidence_support_need",
    category: "CONFIDENCE_AND_SUPPORT",
    purpose: "Select support intensity without inferring mental health.",
    promptKey: "diagnosis.confidence.prompt",
    helpTextKey: "diagnosis.confidence.help",
    title: { en: "Support level", fr: "Niveau de soutien" },
    prompt: { en: "How much support would help you move forward?", fr: "Quel niveau de soutien vous aiderait à avancer ?" },
    helpText: { en: "PATHZY uses this to guide pace and clarity, not to judge you.", fr: "PATHZY utilise cela pour adapter le rythme et la clarté, pas pour vous juger." },
    whyAsked: { en: "Support needs affect how PATHZY explains and orders actions.", fr: "Les besoins de soutien influencent l'explication et l'ordre des actions." },
    answerType: "SINGLE_SELECT",
    options: [option("LIGHT", "A light checklist is enough", "Une simple liste suffit"), option("GUIDED", "Step-by-step guidance", "Un accompagnement étape par étape"), option("HIGH", "High support and examples", "Beaucoup de soutien et d'exemples"), declined],
    requiredness: "OPTIONAL",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "always_helpful_after_core", reason: "Support intensity improves usability." }],
    skipRules: [{ ruleId: "defer_optional", reason: "Not required to complete diagnosis." }],
    branchRules: [{ ruleId: "support_intensity_mode", reason: "Can select high-guidance presentation." }],
    affectedIntelligenceDimensions: ["CONFIDENCE_AND_SUPPORT_READINESS"],
    affectedBarriers: ["CONFIDENCE_AND_SUPPORT_NEED"],
    affectedPathways: ["SUPPORTED_EMPLOYMENT"],
    countryContextDependencies: [],
    literacyLevel: "PLAIN_LANGUAGE",
    expectedEffort: "LOW",
    priority: 150
  }),
  q({
    questionId: "pathway_preference_signal",
    category: "PATHWAY_PREFERENCES",
    purpose: "Capture preferred route signals after critical constraints are known.",
    promptKey: "diagnosis.pathway.prompt",
    helpTextKey: "diagnosis.pathway.help",
    title: { en: "Preferred route", fr: "Parcours préféré" },
    prompt: { en: "Which route feels most useful right now?", fr: "Quel parcours semble le plus utile maintenant ?" },
    helpText: { en: "This is a preference, not a final decision.", fr: "C'est une préférence, pas une décision finale." },
    whyAsked: { en: "Preference helps PATHZY order pathway options once blockers are known.", fr: "La préférence aide PATHZY à ordonner les parcours une fois les blocages connus." },
    answerType: "RANKING",
    options: [option("JOB_NOW", "Find work soon", "Trouver du travail bientôt"), option("LEARNERSHIP_OR_INTERNSHIP", "Internship, learnership, or apprenticeship", "Stage, learnership ou apprentissage"), option("SKILLS_FIRST", "Build skills first", "Développer les compétences d'abord"), option("SELF_EMPLOYMENT", "Freelance or small business", "Freelance ou petite activité"), unknown],
    requiredness: "OPTIONAL",
    sensitivity: "NONE",
    eligibilityRules: [{ ruleId: "ask_after_core", reason: "Preference is useful after blockers are understood." }],
    skipRules: [{ ruleId: "defer_until_core_complete", reason: "Preference should not override critical dependencies." }],
    branchRules: [],
    affectedIntelligenceDimensions: ["CAREER_DIRECTION_READINESS"],
    affectedBarriers: [],
    affectedPathways: ["DIRECT_EMPLOYMENT", "LEARNERSHIP", "APPRENTICESHIP", "SKILLS_FIRST_TRANSITION", "SELF_EMPLOYMENT"],
    countryContextDependencies: ["pathway_context"],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 160
  }),
  q({
    questionId: "career_change_return_context",
    category: "CAREER_CHANGE_OR_RETURN",
    purpose: "Clarify transition context for career changers or return-to-work users.",
    promptKey: "diagnosis.transition.prompt",
    helpTextKey: "diagnosis.transition.help",
    title: { en: "Career transition", fr: "Transition professionnelle" },
    prompt: { en: "Are you changing direction or returning after a break?", fr: "Changez-vous de direction ou revenez-vous après une pause ?" },
    helpText: { en: "PATHZY can focus on transferable evidence and recent confidence-building steps.", fr: "PATHZY peut se concentrer sur les preuves transférables et les étapes récentes." },
    whyAsked: { en: "Transition context affects evidence, confidence, and pathway selection.", fr: "Le contexte de transition influence les preuves, la confiance et les parcours." },
    answerType: "SINGLE_SELECT",
    options: [option("CAREER_CHANGE", "Changing career direction", "Changement de carrière"), option("RETURN_TO_WORK", "Returning after a break", "Retour après une pause"), option("BOTH", "Both", "Les deux"), option("NEITHER", "Neither", "Ni l'un ni l'autre"), declined],
    requiredness: "CONDITIONAL",
    sensitivity: "MEDIUM",
    eligibilityRules: [{ ruleId: "ask_when_transition_signal_detected", reason: "Current situation or evidence suggests transition context." }],
    skipRules: [{ ruleId: "skip_when_not_transition", reason: "Not relevant to all users." }],
    branchRules: [{ ruleId: "transferable_evidence_path", reason: "Transition users need transferable evidence questions." }],
    affectedIntelligenceDimensions: ["EXPERIENCE_READINESS", "CONFIDENCE_AND_SUPPORT_READINESS"],
    affectedBarriers: ["CAREER_TRANSITION_SUPPORT_NEED"],
    affectedPathways: ["CAREER_CHANGE", "RETURN_TO_WORK", "SKILLS_FIRST_TRANSITION"],
    countryContextDependencies: [],
    literacyLevel: "STANDARD",
    expectedEffort: "LOW",
    priority: 170
  })
];

export function diagnosisQuestionById(questionId?: string | null) {
  if (!questionId) return null;
  return employmentDiagnosisQuestionRegistry.find((question) => question.questionId === questionId) ?? null;
}

export function localizedDiagnosisOption(optionValue: string, options: DiagnosisOption[], language: SupportedLanguageCode) {
  return options.find((option) => option.code === optionValue)?.label[language] ?? optionValue;
}
