import { appRoutes } from "@/lib/navigation/routes";
import { supportIntensityLevels } from "../domain/support-intensity";
import { createConfidenceAssessment } from "../engine/calculate-confidence";
import type { ActionDefinition } from "./action-models";
import { EMPLOYMENT_ACTION_ENGINE_VERSION_3E } from "./action-version";

const rawPathzyActionRegistry: ActionDefinition[] = [
  {
    code: "COMPLETE_PROFESSIONAL_IDENTITY",
    category: "IDENTITY_COMPLETION",
    title: "Complete your Professional Identity",
    plainLanguageExplanation: "PATHZY needs the core facts about your situation, goal, location, availability and evidence before it can guide you reliably.",
    reasonCodes: ["identity.incomplete", "source_of_truth.required"],
    urgency: "HIGH",
    effort: "LOW",
    impact: "FOUNDATIONAL",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.professionalIdentity },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["Required Professional Identity sections are confirmed.", "Completion engine marks setup ready for Employment Diagnosis."],
    evidenceSignals: ["professional_identity_completion"],
    pathwaySignals: [],
    barrierSignals: ["INCOMPLETE_PROFESSIONAL_IDENTITY"],
    missingInformationSignals: ["INCOMPLETE_PROFESSIONAL_IDENTITY"],
    diagnosisSignals: [],
    presentationMode: "HIGH_GUIDANCE"
  },
  {
    code: "COMPLETE_EMPLOYMENT_DIAGNOSIS",
    category: "EMPLOYMENT_DIAGNOSIS",
    title: "Complete your Employment Diagnosis",
    plainLanguageExplanation: "The diagnosis helps PATHZY understand practical constraints, support needs and next-step urgency without overwriting your Professional Identity.",
    reasonCodes: ["diagnosis.partial", "support_needs.unknown"],
    urgency: "HIGH",
    effort: "LOW",
    impact: "FOUNDATIONAL",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.discovery },
    prerequisites: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    blockedByActionCodes: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    completionCriteria: ["Diagnosis status is enough for intelligence.", "High-value diagnosis questions are answered or explicitly declined."],
    evidenceSignals: ["employment_diagnosis_result"],
    pathwaySignals: [],
    barrierSignals: ["PRACTICAL_ACCESS_CONSTRAINT"],
    missingInformationSignals: [],
    diagnosisSignals: ["PARTIAL", "NEEDS_REVIEW"],
    presentationMode: "HIGH_GUIDANCE"
  },
  {
    code: "CLARIFY_WORK_ELIGIBILITY",
    category: "IDENTITY_COMPLETION",
    title: "Clarify your work eligibility",
    plainLanguageExplanation: "PATHZY needs a confirmed work-eligibility answer before recommending actions that may depend on permission, documents or eligibility.",
    reasonCodes: ["work_eligibility.uncertain", "hard_eligibility.not_guessed"],
    urgency: "HIGH",
    effort: "LOW",
    impact: "FOUNDATIONAL",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.professionalIdentity, action: "section=workAuthorization" },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["Work eligibility is confirmed, not inferred from nationality."],
    evidenceSignals: ["work_authorisation"],
    pathwaySignals: [],
    barrierSignals: ["WORK_ELIGIBILITY_UNCERTAIN"],
    missingInformationSignals: ["WORK_AUTHORIZATION_UNCLEAR"],
    diagnosisSignals: ["WORK_ELIGIBILITY_UNCERTAIN"],
    presentationMode: "HIGH_GUIDANCE"
  },
  {
    code: "ADD_EVIDENCE_FOR_KEY_SKILLS",
    category: "EVIDENCE_STRENGTHENING",
    title: "Add evidence for your strongest skills",
    plainLanguageExplanation: "Add examples, projects, responsibilities or documents so PATHZY can use your skills truthfully in documents and applications.",
    reasonCodes: ["evidence_gap.skills", "unsupported_claims.not_used_as_verified"],
    urgency: "MEDIUM",
    effort: "MEDIUM",
    impact: "HIGH",
    repeatability: "ONGOING",
    destination: { route: appRoutes.professionalIdentity, action: "section=skills" },
    prerequisites: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    blockedByActionCodes: [],
    completionCriteria: ["At least one key skill has supporting evidence.", "Unsupported claims are reviewed or removed."],
    evidenceSignals: ["skills", "projects", "experience", "documents"],
    pathwaySignals: [],
    barrierSignals: ["UNSUPPORTED_SKILL_CLAIMS"],
    missingInformationSignals: ["SKILLS_EVIDENCE_MISSING", "EVIDENCE_GAPS_PRESENT"],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "CREATE_FIRST_CV",
    category: "DOCUMENT_PREPARATION",
    title: "Create your PATHZY CV",
    plainLanguageExplanation: "A strong CV turns your confirmed Professional Identity into a document you can review, improve and use for applications.",
    reasonCodes: ["cv.required_for_application", "documents.value_before_paywall"],
    urgency: "HIGH",
    effort: "MEDIUM",
    impact: "HIGH",
    repeatability: "ONCE",
    destination: { route: appRoutes.professionalIdentityCv, action: "intent=build" },
    prerequisites: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    blockedByActionCodes: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    completionCriteria: ["A CV draft exists.", "The user can preview the CV before any premium action."],
    evidenceSignals: ["professional_identity", "cv_document"],
    pathwaySignals: ["DIRECT_EMPLOYMENT", "ENTRY_LEVEL_EMPLOYMENT", "PROFESSIONAL_EMPLOYMENT"],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "CREATE_COVER_LETTER",
    category: "DOCUMENT_PREPARATION",
    title: "Create a cover letter draft",
    plainLanguageExplanation: "Use your confirmed profile and CV to prepare a focused cover letter for a job you choose.",
    reasonCodes: ["cover_letter.after_cv", "application_package.preparation"],
    urgency: "MEDIUM",
    effort: "MEDIUM",
    impact: "MEDIUM",
    repeatability: "PER_OPPORTUNITY",
    destination: { route: appRoutes.professionalIdentityCoverLetter },
    prerequisites: ["CREATE_FIRST_CV"],
    blockedByActionCodes: ["CREATE_FIRST_CV"],
    completionCriteria: ["A cover letter draft exists for a target opportunity or general role family."],
    evidenceSignals: ["cv_document", "professional_identity"],
    pathwaySignals: ["DIRECT_EMPLOYMENT", "PROFESSIONAL_EMPLOYMENT"],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "PREPARE_LINKEDIN_PROFILE",
    category: "DOCUMENT_PREPARATION",
    title: "Prepare your LinkedIn profile",
    plainLanguageExplanation: "Turn your confirmed profile into a clear online professional presence where that is useful for your chosen pathway.",
    reasonCodes: ["online_profile.pathway_support", "documents.reuse_identity"],
    urgency: "LOW",
    effort: "MEDIUM",
    impact: "MEDIUM",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.professionalIdentityLinkedin },
    prerequisites: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    blockedByActionCodes: [],
    completionCriteria: ["LinkedIn draft sections are reviewed and saved."],
    evidenceSignals: ["professional_identity", "linkedin_draft"],
    pathwaySignals: ["PROFESSIONAL_EMPLOYMENT", "SKILLED_EMPLOYMENT", "FREELANCE_WORK"],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "FIND_RELEVANT_OPPORTUNITIES",
    category: "JOB_SEARCH",
    title: "Find suitable opportunities",
    plainLanguageExplanation: "Look for roles that match your confirmed profile, practical constraints and current pathway.",
    reasonCodes: ["job_search.next_after_documents", "matching.must_be_explainable"],
    urgency: "MEDIUM",
    effort: "MEDIUM",
    impact: "HIGH",
    repeatability: "ONGOING",
    destination: { route: appRoutes.opportunities },
    prerequisites: ["CREATE_FIRST_CV"],
    blockedByActionCodes: ["CREATE_FIRST_CV"],
    completionCriteria: ["At least one suitable opportunity is saved, reviewed or dismissed with a reason."],
    evidenceSignals: ["opportunity_review"],
    pathwaySignals: ["DIRECT_EMPLOYMENT", "ENTRY_LEVEL_EMPLOYMENT", "TEMPORARY_WORK", "PART_TIME_WORK"],
    barrierSignals: ["MARKET_OR_STRUCTURAL_BARRIER"],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "ANALYSE_TARGET_JOB",
    category: "APPLICATION_PREPARATION",
    title: "Analyse a target job",
    plainLanguageExplanation: "Compare one job advert with your confirmed profile before tailoring documents or deciding whether to apply.",
    reasonCodes: ["job_intelligence.requires_user_choice", "truthful_targeting"],
    urgency: "MEDIUM",
    effort: "LOW",
    impact: "HIGH",
    repeatability: "PER_OPPORTUNITY",
    destination: { route: appRoutes.opportunities, action: "job-intelligence" },
    prerequisites: ["FIND_RELEVANT_OPPORTUNITIES"],
    blockedByActionCodes: [],
    completionCriteria: ["Job requirements are structured.", "Strengths, gaps and uncertainties are visible to the user."],
    evidenceSignals: ["job_requirements", "canonical_profile_evidence"],
    pathwaySignals: [],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "PREPARE_APPLICATION_PACKAGE",
    category: "APPLICATION_PREPARATION",
    title: "Prepare an application package",
    plainLanguageExplanation: "Prepare a truthful CV and cover letter for one target job, with the user reviewing everything before submission.",
    reasonCodes: ["human_approval.required", "targeted_documents.after_job_analysis"],
    urgency: "MEDIUM",
    effort: "MEDIUM",
    impact: "HIGH",
    repeatability: "PER_OPPORTUNITY",
    destination: { route: appRoutes.employmentCenter, action: "prepare-application" },
    prerequisites: ["ANALYSE_TARGET_JOB", "CREATE_FIRST_CV"],
    blockedByActionCodes: ["CREATE_FIRST_CV"],
    completionCriteria: ["Targeted documents are prepared.", "Unsupported claims are blocked or flagged.", "User approval remains required."],
    evidenceSignals: ["target_job", "cv_document", "cover_letter"],
    pathwaySignals: [],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "TRACK_APPLICATION",
    category: "FOLLOW_UP",
    title: "Track an application",
    plainLanguageExplanation: "Record what happened next so PATHZY can help with follow-up, interviews and safe progress tracking.",
    reasonCodes: ["application_tracker.operational_view", "no_auto_apply"],
    urgency: "MEDIUM",
    effort: "LOW",
    impact: "MEDIUM",
    repeatability: "PER_OPPORTUNITY",
    destination: { route: appRoutes.applications },
    prerequisites: ["PREPARE_APPLICATION_PACKAGE"],
    blockedByActionCodes: [],
    completionCriteria: ["Application status, next action and key dates are tracked."],
    evidenceSignals: ["application_record"],
    pathwaySignals: [],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "PREPARE_FOR_INTERVIEW",
    category: "INTERVIEW_PREPARATION",
    title: "Prepare for an interview",
    plainLanguageExplanation: "Use the job requirements and your confirmed evidence to practise truthful, relevant interview answers.",
    reasonCodes: ["interview.prep_after_application", "evidence_grounded_answers"],
    urgency: "HIGH",
    effort: "MEDIUM",
    impact: "HIGH",
    repeatability: "PER_OPPORTUNITY",
    destination: { route: appRoutes.interview },
    prerequisites: ["TRACK_APPLICATION"],
    blockedByActionCodes: [],
    completionCriteria: ["Practice questions, evidence points and questions for the employer are prepared."],
    evidenceSignals: ["interview_record", "job_requirements", "canonical_profile_evidence"],
    pathwaySignals: [],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  },
  {
    code: "PLAN_PRACTICAL_ACCESS",
    category: "PRACTICAL_SUPPORT",
    title: "Plan around practical constraints",
    plainLanguageExplanation: "Choose next steps that work with your transport, device, internet, care or schedule realities.",
    reasonCodes: ["practical_constraints.support_not_judgement", "access_shapes_workflow"],
    urgency: "HIGH",
    effort: "LOW",
    impact: "URGENT_SUPPORT",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.discovery },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["Practical constraints are confirmed.", "PATHZY adapts the plan without lowering capability assumptions."],
    evidenceSignals: ["diagnosis_practical_constraints"],
    pathwaySignals: ["TEMPORARY_WORK", "PART_TIME_WORK", "SUPPORTED_EMPLOYMENT"],
    barrierSignals: ["PRACTICAL_ACCESS_CONSTRAINT"],
    missingInformationSignals: [],
    diagnosisSignals: ["PRACTICAL_ACCESS_CONSTRAINT", "TRANSPORT_OR_SHIFT_LIMIT", "DIGITAL_ACCESS_SUPPORT"],
    presentationMode: "HIGH_GUIDANCE"
  },
  {
    code: "EXPLORE_IMMEDIATE_INCOME_OPTIONS",
    category: "PATHWAY_EXPLORATION",
    title: "Explore immediate income options",
    plainLanguageExplanation: "If income is urgent, PATHZY should prioritise practical short-term options while protecting your longer-term career plan.",
    reasonCodes: ["income_urgency.prioritise_short_term", "long_term_path_not_abandoned"],
    urgency: "IMMEDIATE",
    effort: "LOW",
    impact: "URGENT_SUPPORT",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.employmentCenter, action: "immediate-income" },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["Short-term pathway options are reviewed.", "The user chooses whether any fit their situation."],
    evidenceSignals: ["diagnosis_immediate_income"],
    pathwaySignals: ["TEMPORARY_WORK", "PART_TIME_WORK", "INFORMAL_OR_COMMUNITY_WORK", "SUPPORTED_EMPLOYMENT"],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: ["URGENT_INCOME", "IMMEDIATE_INCOME_NEED"],
    presentationMode: "HIGH_GUIDANCE"
  },
  {
    code: "INVESTIGATE_QUALIFICATION_RECOGNITION",
    category: "PATHWAY_EXPLORATION",
    title: "Check qualification recognition",
    plainLanguageExplanation: "If qualification recognition is uncertain, PATHZY should keep the pathway visible but avoid claiming eligibility until it is confirmed.",
    reasonCodes: ["qualification_recognition.uncertain", "do_not_overclaim"],
    urgency: "MEDIUM",
    effort: "MEDIUM",
    impact: "HIGH",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.professionalIdentity, action: "section=education" },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["Recognition status or next verification step is recorded."],
    evidenceSignals: ["education", "certificates", "country_context"],
    pathwaySignals: ["QUALIFICATION_RECOGNITION", "BRIDGING_EDUCATION", "PROFESSIONAL_EMPLOYMENT"],
    barrierSignals: [],
    missingInformationSignals: ["QUALIFICATION_RECOGNITION_EVIDENCE"],
    diagnosisSignals: ["QUALIFICATION_RECOGNITION_EVIDENCE"],
    presentationMode: "STANDARD"
  },
  {
    code: "CONFIRM_LICENCE_OR_CERTIFICATE",
    category: "EVIDENCE_STRENGTHENING",
    title: "Confirm licence or certificate evidence",
    plainLanguageExplanation: "Some pathways may need licence or certificate evidence. PATHZY should ask for proof before relying on that route.",
    reasonCodes: ["licence_or_certificate.evidence_required", "eligibility.not_assumed"],
    urgency: "MEDIUM",
    effort: "LOW",
    impact: "HIGH",
    repeatability: "WHEN_STALE",
    destination: { route: appRoutes.professionalIdentity, action: "section=credentials" },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["Licence or certificate evidence is uploaded, confirmed or marked not applicable."],
    evidenceSignals: ["licences", "certificates", "supporting_documents"],
    pathwaySignals: ["LICENCE_OR_CERTIFICATE", "SKILLED_EMPLOYMENT"],
    barrierSignals: [],
    missingInformationSignals: ["LICENCE_OR_CERTIFICATE_EVIDENCE"],
    diagnosisSignals: ["SECURITY_REGISTRATION_EVIDENCE"],
    presentationMode: "STANDARD"
  },
  {
    code: "PRACTISE_WITH_COACH",
    category: "HUMAN_SUPPORT",
    title: "Use guided support",
    plainLanguageExplanation: "Use PATHZY support to work through the next step slowly and clearly when the process feels confusing or overwhelming.",
    reasonCodes: ["support_intensity.high", "plain_language.helpful"],
    urgency: "MEDIUM",
    effort: "LOW",
    impact: "MEDIUM",
    repeatability: "ONGOING",
    destination: { route: appRoutes.coach },
    prerequisites: [],
    blockedByActionCodes: [],
    completionCriteria: ["The user receives guidance for the current step and can decide what to do next."],
    evidenceSignals: ["support_needs"],
    pathwaySignals: [],
    barrierSignals: [],
    missingInformationSignals: [],
    diagnosisSignals: ["PLAIN_LANGUAGE_SUPPORT", "SOME_HELP", "HIGH_GUIDANCE"],
    presentationMode: "ASSISTED"
  },
  {
    code: "IMPROVE_PRIORITY_SKILL",
    category: "SKILL_DEVELOPMENT",
    title: "Improve one priority skill",
    plainLanguageExplanation: "Choose one skill gap that matters for your pathway and turn it into a practical learning or evidence-building step.",
    reasonCodes: ["skill_gap.prioritise_one", "avoid_generic_skill_lists"],
    urgency: "LOW",
    effort: "MEDIUM",
    impact: "MEDIUM",
    repeatability: "ONGOING",
    destination: { route: appRoutes.skills },
    prerequisites: ["COMPLETE_PROFESSIONAL_IDENTITY"],
    blockedByActionCodes: [],
    completionCriteria: ["One priority skill gap is selected.", "A practical improvement step or evidence task is recorded."],
    evidenceSignals: ["skills", "evidence_gaps", "pathway_requirements"],
    pathwaySignals: ["SKILLS_FIRST_TRANSITION", "CAREER_CHANGE", "BRIDGING_EDUCATION"],
    barrierSignals: [],
    missingInformationSignals: ["SKILL_GAP"],
    diagnosisSignals: [],
    presentationMode: "STANDARD"
  }
];

const defaultActionConfidence = createConfidenceAssessment({
  completeness: 0.65,
  evidence: 0.45,
  ruleCertainty: 0.78,
  countryContext: 0.35,
  rationale: ["phase3e.action.registry.default_confidence"]
});

export const pathzyActionRegistry: ActionDefinition[] = rawPathzyActionRegistry.map((action) => ({
  titleKey: `actions.${action.code}.title`,
  explanationKey: `actions.${action.code}.explanation`,
  route: action.destination.route,
  affectedReadinessDimensions: [],
  addressedBarrierCodes: action.barrierSignals,
  supportedPathwayCodes: action.pathwaySignals,
  eligibilityRules: action.reasonCodes,
  contraindications: ["Do not recommend if known legal, safety or user-declined constraints make the action unsuitable."],
  supportIntensityCompatibility: [...supportIntensityLevels],
  countryContextRequirements: ["Use country adapters only for stable generic constraints; do not invent live programmes or salary values."],
  evidenceReferences: action.evidenceSignals,
  confidence: defaultActionConfidence,
  engineVersion: EMPLOYMENT_ACTION_ENGINE_VERSION_3E,
  ...action
}));

export function actionByCode(code: string) {
  return pathzyActionRegistry.find((action) => action.code === code) ?? null;
}
